const apis = {
  // App
  permissions: "/api/userpermission/list",
  database: "/api/userdatabase/get",
  studyClass: "/api/study_class/teacher_class",
  saveToken: "/api/notification/createtoken",
  auth: "/ocsauth/oauth",

  // Users
  userInfo: "/api/user/profile/info",
  userUpdate: "/api/user/profile/update",
  userInfoChangePhone: "/api/user/profile/changePhone",
  userChangeEmail: "/api/user/profile/changeEmail",
  userChangePassword: "/api/user/profile/changePassword",

  // module teacher
  academicYear: "/api/academy/list",

  user: {
    getUser: {
      List: "/api/user/list",
    },
    databaseByGroup: {
      List: "api/usergroup/database/list",
      Create: "api/usergroup/database/create",
      Delete: "api/usergroup/database/delete",
    },
    databaseByUser: {
      list: "api/user/database/list",
      create: "api/user/database/create",
      delete: "api/user/database/delete",
    },
    userGroup: {
      list: "api/usergroup/list",
      create: "api/usergroup/create",
      update: "api/usergroup/update",
      delete: "api/usergroup/delete",
    },
    userGroupDetail: {
      list: "api/usergroup/detail/list",
      create: "api/usergroup/detail/create",
      delete: "api/usergroup/detail/delete",
    },
    notification: {
      list: "/api/notification/get",
      getUnread: "/api/notification/countunread",
      markAllRead: "/api/notification/markallasread",
      markRead: "/api/notification/markasread",
      createToken: "/api/notification/createtoken",
      delete: "/api/notification/delete",
      deleteAll: "/api/notification/deleteall",
      markAsReadByType: "api/notification/markasreadbytype",
      countUnreadByAppModes: "api/notification/countunreadbyappmodes",
    },
    permission: {
      list: "api/permission/list",
      create: "api/permission/Create",
      dataPermissionList: "api/permission/data/list",
      dataPermissionCreate: "api/permission/data/Create",
      dataPermissionToggleDatapermission:
        "api/permission/data/toggledatapermission",
      dataPermissionToggleReportPermission:
        "api/permission/data/togglereportpermission",
    },
    userAuthentication: {},
  },

  productsAndServices: {
    product: {
      list: "api/ProductList/get",
      create: "api/ProductList/add",
      update: "api/ProductList/update",
      delete: "api/ProductList/delete",
      validateCode: "api/ProductList/validatecode",
      validateBarCode: "api/ProductList/validatebarcode",

      getAssembly: "api/productList/GetAssembly",
      addAssembly: "api/productlist/addassembly",
      editAssembly: "api/productlist/editassembly",
      deleteAssembly: "api/productlist/deleteassembly",
    },
    unitConversion: {
      list: "api/unitConversion/get",
      create: "api/unitConversion/add",
      delete: "api/unitConversion/delete",
      update: "api/unitConversion/update",
      validate: "api/unitconversion/validatecode",
    },
    productCategory: {
      list: "api/itemcategory/get",
      add: "api/itemcategory/add",
      update: "api/itemcategory/update",
      delete: "api/itemcategory/delete",
      validate: "api/itemcategory/validatecode",
    },
    productLine: {
      list: "api/ProductLine/get",
      add: "api/ProductLine/add",
      update: "api/ProductLine/update",
      delete: "api/ProductLine/delete",
      validate: "api/productline/validatecode",
    },
    productLabel: {
      list: "/api/product_label/list",
      chartAccount: "/api/ChartAccount/Get",
      analysis: {
        headerList: "/api/analysis/header/list",
        headerFindAndSys: "/api/analysis/header/find_anal_sys",
        detail: "/api/analysis/detail/list_by_header",
      },
      update: "/api/product_label/update",
    },
  },

  scoringAndGrading: {
    academicYearExam: {
      listSetup: "api/academic_year_exam/list_setup",
      addSetup: "api/academic_year_exam/add_setup",
      deleteSetup: "api/academic_year_exam/delete_setup",
      examSetupList: "api/academic_year_exam/exam_setup_add_list",
      listDetail: "api/academic_year_exam/list",
      addDetail: "api/academic_year_exam/add",
      updateDetail: "api/academic_year_exam/update",
      deleteDetail: "api/academic_year_exam/delete",
      checkExistExamCode: "api/academic_year_exam/check_exist_exam_code",
      examDetailList: "api/academic_year_exam/exam_add_list",
    },
    scoringByClass: {
      deleteAllScore: "",
      deleteScore: "",
    },
    examSetup: {
      list: "/api/exam_subject_setup/list",
    },
    examStructure: {
      list: "api/examsetup/list",
      create: "api/examsetup/create",
      update: "api/examsetup/update",
      delete: "api/examsetup/delete",
      checkedCode: "api/examsetup/checkedcode",
    },
    exam: {
      list: "api/exam/list",
      create: "api/exam/create",
      update: "api/exam/update",
      delete: "api/exams/delete",
      checkedCode: "api/exam/checkedcode",
    },
  },

  profile: {
    signature: {
      list: "api/employee/get_signature",
      add: "api/employee/add_file_signature",
      delete: "/api/employee/delete_signature",
    },
  },

  academic: {
    academicList: "/api/academy/list",
    roomlist: "/api/room/list",
    schedule: {
      list: "/api/schedule/list",
      studyClassListFilter: "/api/studyclass/listfilter",
      print: "/api/schedule/print",
      delete: "/api/schedule/delete",
      periodTypeByClass: "api/schedule/period_type_by_class",
      periodByClass: "api/schedule/periods_by_class",
      detail: {
        listBySession: "api/schedule_detail/list_by_session",
        save: "api/schedule_detail/save",
        delete: "api/schedule_detail/delete",
        checkExistData: "api/schedule_detail/check_exist_data",
        weekList: "api/shedule_detail/week_list",
        checkedRoomIsBusy: "api/schedule_detail/checked_room_is_busy",
        checkedEmployeeIsBusy: "api/schedule_detail/checked_emp_is_busy",
      },
    },
  },

  sale: {
    saleInvoice: {
      list: "api/saleinvoice/list",
      detail: "api/saleinvoice/detail",
      create: "api/saleinvoice/create",
      update: "api/saleinvoice/update",
      hold: "api/saleinvoice/hold",
      release: "api/saleinvoice/release",
      post: "api/saleinvoice/post",
      void: "api/saleinvoice/void",
    },
    saleType: {
      list: "api/saletype/list",
      create: "api/saletype/create",
      update: "api/saletype/update",
      delete: "api/saletype/delete",
      checkExistCode: "api/saletype/check_exist_code",
    },
    issueInvoice: {
      getClass: "api/IssueInvoice/GetClass",
      apiGetSaleInvoiceList: "api/IssueInvoice/GetSaleInvoiceList",
      getBasicInfoInvoiceDetial: "api/IssueInvoice/GetBasicInfoInvoiceDetial",
      getInfoInvoiceDetail: "api/IssueInvoice/GetInfoInvoiceDetail",
      getInvoiceDetail: "api/IssueInvoice/GetInvoiceDetail",
      getPrintInvoiceInfo: "api/IssueInvoice/GetPrintInvoiceInfo",
    },
    customer: {
      basic: {
        list: "api/customer/basic/list",
        create: "api/customer/basic/create",
        update: "api/customer/basic/update",
        delete: "api/customer/basic/delete",
        read: "api/customer/basic/read",
      },
      account: {
        list: "api/customer/account/list",
        create: "api/customer/account/create",
        update: "api/customer/account/update",
        delete: "api/customer/account/delete",
        read: "api/customer/account/read",
        analysisHeaders: "api/customer/account/analysisheaders",
        analysisDetail: "api/customer/account/analysisdetail",
      },
      delivery: {
        list: "api/customer/delivery/list",
        create: "api/customer/delivery/create",
        update: "api/customer/delivery/update",
        delete: "api/customer/delivery/delete",
        read: "api/customer/delivery/read",
        updateForCust: "api/customer/delivery/updateforcust",
      },
      item: {
        list: "api/customer/item/list",
        create: "api/customer/item/create",
        update: "api/customer/item/update",
        delete: "api/customer/item/delete",
        read: "api/customer/item/read",
      },
    },
    cashReceipt: {
      // list: "api/cashreceipt/get",
      // listByDatabases: "api/cashreceipt/list_by_databases",
      // detail: "api/cashreceipt/detail",
      // create: "api/cashreceipt/create",
      // listingReport: "api/cashreceipt/listingreport",
      // printReceipt: "api/cashreceipt/printreceipt",
      // savePrintReceiptLog: "api/cashreceipt/saveprintlog",
      // receiptSummary: "api/cashreceipt/receipt_summary",
      // receiptDetail: "api/cashreceipt/receipt_detail",
      // saleReceipt: "api/cashreceipt/sale_receipt",
      // listCashier: "api/cashreceipt/listcashier",
      list: "api/cash_receipt/list",
      detail: "api/cash_receipt/detail",
      create: "api/cash_receipt/create",
      listing: "api/cash_receipt/listing_report",
      printReceipt: "api/cash_receipt/print_receipt",
      savePrintReceiptLog: "api/cash_receipt/save_printlog",
      receiptSummary: "api/cash_receipt/receipt_summary",
      cashReceiptReport: "api/cash_receipt/cash_receipt_report",
      listCashier: "api/cash_receipt/list_cashier",
      cashReceiptCurrency: "api/cash_receipt/cash_receipt_currency",
      checkedReference: "api/cash_receipt/already_exist",
    },
    saleDefinition: {
      get: "api/saledefinition/get",
    },
    receiptType: {
      list: "api/receipttype/list",
      update: "api/receipttype/update",
      create: "api/receipttype/create",
      delete: "api/receipttype/delete",
      validate: "api/receipttype/validatecode",
    },
  },

  system: {
    exchangeRate: {
      list: "api/exchange_rate/list",
      get: "api/exchange_rate/get",
      create: "api/exchange_rate/create",
      update: "api/exchange_rate/update",
      delete: "api/exchange_rate/delete",
    },
    currency: {
      list: "api/currency/list",
      create: "api/currency/create",
      update: "api/currency/update",
      delete: "api/currency/delete",
      checkCodeExist: "api/currency/check_code_exist",
    },
    currencyNote: {
      list: "api/currency/note/list",
      create: "api/currency/note/create",
      update: "api/currency/note/update",
      delete: "api/currency/note/delete",
      uploadPicture: "api/currency/note/upload_picture",
    },
    analysisDetail: {
      list: "api/analysis/detail/list",
      disabledAnalysisCode: "api/analysis/detail/disabled_analysis_code",
      listByHeader: "api/analysis/detail/list_by_header",
      create: "api/analysis/detail/create",
      update: "api/analysis/detail/update",
      delete: "api/analysis/detail/delete",
      read: "api/analysis/detail/read",
      get: "api/analysisdetail/getanalysisdetail",
      checkExistCode: "api/analysis/detail/checkexistcode",
    },
    analysisHeader: {
      list: "api/analysis/header/list",
      create: "api/analysis/header/create",
      update: "api/analysis/header/update",
      delete: "api/analysis/header/delete",
      read: "api/analysis/header/read",
      checkExistCode: "api/analysis/header/checkexistcode",
      findAnalSys: "api/analysis/header/find_anal_sys",
    },
    autoNumber: {
      list: "api/autonumber/list",
      read: "api/autonumber/get",
      create: "api/autonumber/add",
      update: "api/autonumber/update",
      delete: "api/autonumber/delete",
    },
    database: {
      getDatabaseInfo: "api/database/getinfo",
      hasGlobalDatabase: "api/database/has_global",
      list: "api/database/list",
      create: "api/database/create",
      update: "api/database/update",
      delete: "api/database/delete",
      uploadLogo: "api/database/upload_logo",
      deleteLogo: "api/database/delete_logo",
      publicList: "api/database/public/list",
      publicCheckExist: "api/database/public/checkexist",
    },
    deviceSetting: {
      deviceDB: "api/device_setting/device_db",
      deviceACSerial: "api/device_setting/device_acserial",
    },
    nationality: {
      list: "api/nationality/list",
      create: "api/nationality/create",
      update: "api/nationality/update",
      delete: "api/nationality/delete",
      validateCode: "api/nationality/validatecode",
    },
    accounting: {
      list: "api/accounting/period/list",
      create: "api/accounting/period/create",
      next: "api/accounting/period/next",
      block: "api/accounting/period/block",
    },
    systemSync: {
      syncData: "api/systemsync/sync",
      updateSyncStatus: "api/Systemsync/update",
    },
    userMessageTemplate: {
      get: "api/user_message_template/get",
      create: "api/user_message_template/add",
      update: "api/user_message_template/update",
      delete: "api/user_message_template/delete",
    },
    approvalRule: {
      listApprovalType: "api/approval_rule/list_approval_type",
      listReferenceType: "api/approval_rule/list_reference_type",
      list: "api/approvalrule/list",
      checkExistCode: "api/approvalrule/checkexistcode",
      create: "api/approvalrule/create",
      update: "api/approvalrule/update",
      delete: "api/approvalrule/delete",
    },
    approvalRuleStep: {
      list: "api/approvalrule/step/list/new",
      create: "api/approvalrule/step/create/new",
      update: "api/approvalrule/step/update/new",
      delete: "api/approvalrule/step/delete/new",
      reorderStep: "api/approvalrule/step/reorder",
    },
    address: {
      list: "api/address/get",
      count: "api/address/count",
      create: "api/address/create",
      update: "api/address/update",
      delete: "api/address/delete",
      validateCode: "api/address/validatecode",
      countryKey: "COUNTRYS",
      provinceKey: "PROVINCES",
      districtKey: "DISTRICTS",
      communeKey: "COMMUNES",
      villageKey: "VILLAGES",
      addressType: "CURRENT",
    },
  },

  inventory: {
    adjustment: {
      list: "api/Adjustment/get",
      listDetail: "api/Adjustment/detail",
      stockList: "api/adjustment/getitemstock",
      create: "api/adjustment/create",
      post: "api/adjustment/post",
      void: "api/adjustment/void",
      checkStatus: "api/adjustment/status",
      reportListing: "api/Adjustment/reportlisting",
      checkedReference: "api/Adjustment/checked_reference",
    },
    adjustmentType: {
      get: "api/adjustmenttype/get",
      add: "api/adjustmenttype/add",
      edit: "api/adjustmenttype/edit",
      delete: "api/adjustmenttype/delete",
      validate: "api/adjustmenttype/validate",
      checkPrintDocument: "api/adjustment_type/check_print_document",
    },
    category: {
      get: "api/itemcategory/get",
      add: "api/itemcategory/add",
      edit: "api/itemcategory/update",
      delete: "api/itemcategory/delete",
      validate: "api/itemcategory/validatecode",
      uploadImage: "api/itemcategory/uploadimage",
    },
    location: {
      get: "api/location/get",
      add: "api/location/add",
      edit: "api/location/edit",
      delete: "api/location/delete",
      validate: "api/location/validate",
    },
    priceByUnit: {
      list: "api/pricebyunit/list",
      create: "api/pricebyunit/create",
      update: "api/pricebyunit/update",
      delete: "api/pricebyunit/delete",
      read: "api/pricebyunit/read",
    },
    productAssembly: {
      list: "api/ProductAssembly/get",
      create: "api/ProductAssembly/add",
      update: "api/ProductAssembly/edit",
      delete: "api/ProductAssembly/delete",
      validate: "api/productAssembly/validate",
    },
    product: {
      list: "api/ProductList/get",
      create: "api/ProductList/add",
      update: "api/ProductList/update",
      delete: "api/ProductList/delete",
      validateCode: "api/ProductList/validatecode",
      validateBarCode: "api/ProductList/validatebarcode",
      getAssembly: "api/productList/GetAssembly",
      addAssembly: "api/productlist/addassembly",
      editAssembly: "api/productlist/editassembly",
      deleteAssembly: "api/productlist/deleteassembly",
    },
    productLabel: {
      list: "api/product_label/list",
      update: "api/product_label/update",
    },
    productLine: {
      get: "api/ProductLine/get",
      add: "api/ProductLine/add",
      edit: "api/ProductLine/update",
      delete: "api/ProductLine/delete",
      validate: "api/productline/validatecode",
    },
    stockBalance: {
      report: "api/stock_balance/report",
    },
    transfer: {
      list: "api/transfer/get",
      listDetail: "api/transfer/get_detail",
      stockList: "api/transfer/getitemstock",
      create: "api/transfer/create",
      post: "api/transfer/post",
      void: "api/transfer/void",
      checkStatus: "api/transfer/status",
      reportListing: "api/transfer/reportlisting",
      checkedReference: "api/transfer/checked_reference",
    },
    transferType: {
      list: "api/stocktransfertype/get",
      create: "api/stocktransfertype/add",
      update: "api/stocktransfertype/edit",
      delete: "api/stocktransfertype/delete",
      validate: "api/stocktransfertype/validate",
      checkPrintDocument: "api/stock_transfer_type/check_print_document",
    },
    unitConversion: {
      list: "api/unitConversion/get",
      create: "api/unitConversion/add",
      delete: "api/unitConversion/delete",
      update: "api/unitConversion/update",
      validate: "api/unitconversion/validatecode",
    },
    inventoryAnalysisDesign: {
      list: "api/inventory_analysis_design/list",
      create: "api/inventory_analysis_design/create",
      update: "api/inventory_analysis_design/update",
      delete: "api/inventory_analysis_design/delete",
      orderNo: "api/inventory_analysis_design/order_no",
    },
    inventoryAnalysisDesignDetail: {
      list: "api/inventory_analysis_design_detail/list",
      create: "api/inventory_analysis_design_detail/create",
      update: "api/inventory_analysis_design_detail/update",
      delete: "api/inventory_analysis_design_detail/delete",
      getType: "api/inventory_analysis_design_detail/get_type",
    },
  },

  purchase: {
    payable: {
      list: "api/payable/list",
      split: "api/payable/split",
      ageReport: "api/payable/agereport",
      listUserCreate: "api/payable/listcreator",
    },
    payment: {
      list: "api/payment/list",
      detail: "api/payment/detail",
      create: "api/payment/create",
      savePrintPaymentLog: "api/payment/saveprintlog",
      listCreator: "api/payment/listcreator",
      printPayment: "api/payment/printpayment",
      checkExistReference: "api/payment/check_exist_reference",
      paymentSummaryReport: "api/payment/report/payment_summary",
      paymentDetailReport: "api/payment/report/payment_detail",
      purchasePaymentReport: "api/payment/report/purchase_payment",
    },
    payemntType: {
      list: "api/paymenttype/list",
      update: "api/paymenttype/update",
      create: "api/paymenttype/create",
      delete: "api/paymenttype/delete",
      validate: "api/paymenttype/validatecode",
    },
    purchaseInvoice: {
      list: "api/purchaseinvoice/list", // method post
      getDetail: "api/purchaseinvoice/detail",
      getLogs: "api/purchaseinvoice/getlogs",
      getPostVoidStatus: "api/purchaseinvoice/getpostvoidstatus",
      save: "api/purchaseinvoice/Create",
      createDebitNote: "api/purchaseinvoice/Createdebitnote",
      update: "api/purchaseinvoice/update",
      hold: "api/purchaseinvoice/hold",
      release: "api/purchaseinvoice/release",
      void: "api/purchaseinvoice/void",
      post: "api/purchaseinvoice/post",
      savePrintLog: "api/purchaseinvoice/saveprintlog",
      listCreator: "api/purchase_invoice/list_creator",
      printPurchaseInvoice: "api/purchaseinvoice/print",
      purchaseSummaryReport: "api/purchase_invoice/purchase_summary_report",
      purchaseDetailReport: "api/purchase_invoice/purchase_detail_report",
    },
    purchaseType: {
      list: "api/purchasetype/list",
      checkExistCode: "api/purchasetype/checkexistcode",
      create: "api/purchasetype/create",
      update: "api/purchasetype/update",
      delete: "api/purchasetype/delete",
    },
    suplier: {
      basic: {
        list: "api/supplier/basic/list",
        create: "api/supplier/basic/create",
        update: "api/supplier/basic/update",
        delete: "api/supplier/basic/delete",
        read: "api/supplier/basic/read",
      },
      account: {
        list: "api/supplier/account/list",
        create: "api/supplier/account/create",
        update: "api/supplier/account/update",
        delete: "api/supplier/account/delete",
        read: "api/supplier/account/read",
        supplierAnalysisHeaders: "api/supplier/account/analysisheaders",
        supplierAnalysisDetail: "api/supplier/account/analysisdetail",
      },
      delivery: {
        list: "api/supplier/delivery/list",
        create: "api/supplier/delivery/create",
        update: "api/supplier/delivery/update",
        delete: "api/supplier/delivery/delete",
        read: "api/supplier/delivery/read",
        updateForSupp: "api/supplier/delivery/updateforsupp",
      },
      item: {
        list: "api/supplier/item/list",
        create: "api/supplier/item/create",
        update: "api/supplier/item/update",
        delete: "api/supplier/item/delete",
        read: "api/supplier/item/read",
      },
    },
  },

  accounting: {
    BSReport: {
      list: "api/bsreport/list",
    },
    chartAccount: {
      list: "api/ChartAccount/Get",
      create: "api/ChartAccount/Add",
      update: "api/chartaccount/edit",
      delete: "api/chartaccount/delete",
      validate: "api/chartaccount/validatecode",
    },
    chartAccountOB: {
      list: "api/chartaccountob/list",
      create: "api/chartaccountob/create",
      update: "api/chartaccountob/update",
      delete: "api/chartaccountob/delete",
    },
    designBSColunm: {
      listColumn: "api/designbscolumn/list",
      createColumn: "api/designbscolumn/create",
      updateColumn: "api/designbscolumn/update",
      deleteColumn: "api/designbscolumn/delete",
    },
    designBSRow: {
      listRow: "api/designbsrow/list",
      moveUpDown: "api/designbsrow/move_up_down",
      createRow: "api/designbsrow/create",
      updateRow: "api/designbsrow/update",
      deleteRow: "api/designbsrow/delete",
    },
    designISColunm: {
      listColumn: "api/designiscolumn/list",
      createColumn: "api/designiscolumn/create",
      updateColumn: "api/designiscolumn/update",
      deleteColumn: "api/designiscolumn/delete",
    },
    designISRow: {
      listRow: "api/designisrow/list",
      moveUpDown: "api/designisrow/move_up_down",
      createRow: "api/designisrow/create",
      updateRow: "api/designisrow/update",
      deleteRow: "api/designisrow/delete",
    },
    GLReport: {
      list: "api/general_ledger/report",
    },
    ISReport: {
      list: "api/isreport/list",
    },
    journalEntry: {
      create: "api/journalentry/create",
      update: "api/journalentry/update",
      hold: "api/journalentry/hold",
      release: "api/journalentry/release",
      post: "api/journalentry/post",
      reverse: "api/journalentry/reverse",
      delete: "api/journalentry/delete",
      read: "api/journalentry/read",
      readDetail: "api/journalentry/readDetail",
      headerList: "api/journalentry/headerlist",
      detailList: "api/journalentry/detaillist",
      checkExitReference: "api/journalentry/check_exist_reference",
      journalForm: "api/journalentry/journal_form",
      journalListing: "api/journalentry/journal_listing",
      generalJournalReport: "api/journalentry/generaljournal_report",
      journalLog: "api/journalentry/log",
    },
    journalType: {
      list: "api/journaltype/list",
      listAnalysisByJournalType: "api/journaltype/analysis_list",
      update: "api/journaltype/update",
      create: "api/journaltype/create",
      delete: "api/journaltype/delete",
      validate: "api/journaltype/validatecode",
    },
    ledgerInterface: {
      header: {
        list: "api/ledgerinterface/header/list",
        create: "api/ledgerinterface/header/create",
        update: "api/ledgerinterface/header/update",
        delete: "api/ledgerinterface/header/delete",
      },
      detail: {
        list: "api/ledgerinterface/detail/list",
        create: "api/ledgerinterface/detail/create",
        update: "api/ledgerinterface/detail/update",
        delete: "api/ledgerinterface/detail/delete",
        chartAccounts: "api/ledgerinterface/detail/chartaccounts",
        calculateDefinitions: "api/ledgerinterface/detail/calculatedefinitions",
      },
    },
    TBReport: {
      list: "api/tbreport/list",
    },
  },

  report: {
    getList: "api/report/getReportList",
    getReportDefinition: "api/report/getReportDefinition",
    getReport: "api/report/getReport",
    add: "api/reportSetting/add",
    import: "api/reportSetting/Import",
    update: "api/reportSetting/update",
    updateReportFile: "api/reportSetting/updatefile",
    changeReportFileFile: "api/reportSetting/changefile",
    remove: "api/reportSetting/Remove",
    getReportTypeList: "api/report/getReportTypeList",
    getReportTypeListActive: "api/report/getReportTypeList/active",
    addReportType: "api/reportType/add",
    updateReportType: "api/reportType/update",
    removeReportType: "api/reportType/Remove",
    uploadXtraReport: "api/upload/XtraReport",
  },

  employeeAttendance: {
    dailyAttendance: {
      list: "api/dailyattendance/list",
      employeeList: "api/dailyattendance/employeelist",
      create: "api/dailyattendance/create",
      delete: "api/dailyattendance/delete",
      shift: "api/dailyattendance/shiftlist",
    },

    monthlyAttendance: {
      list: "api/monthlyattendance/list",
      detail: "api/monthlyattendance/detail",
      monthlyReport: "api/monthlyattendance/monthlyreport",
      monthlySummaryReport: "api/monthlyattendance/monthlysummaryreport",
    },
    timeAdjustment: {
      list: "api/timeadjustment/list",
      create: "api/timeadjustment/create",
      update: "api/timeadjustment/update",
      delete: "api/timeadjustment/delete",
      checkCodeExist: "api/timeadjustment/existcode",
    },
    payroll: {
      list: "api/payroll_formula/list",
      checkExistCode: "api/payroll_formula/check_exist_code",
      create: "api/payroll_formula/create",
      update: "api/payroll_formula/update",
      delete: "api/payroll_formula/delete",
    },
    payrollVariable: {
      list: "api/payroll/variable/list",
      checkExistName: "api/payroll/variable/checkexistname",
      create: "api/payroll/variable/create",
      update: "api/payroll/variable/update",
      delete: "api/payroll/variable/delete",
    },

    calendar: {
      list: "api/calendar/list",
      create: "api/calendar/create",
      update: "api/calendar/update",
      delete: "api/calendar/delete",
      checkExistCode: "api/calendar/existcode"
    },
    attRule: {
      list: "api/employee_attendance_rule/list",
      addEmployee: "api/employee_attendance_rule/add_employee",
      employeeList: "api/employee_attendance_rule/employee_list",
      removeEmployee: "api/employee_attendance_rule/remove_employee",
      create: "api/employee_attendance_rule/create",
      update: "api/employee_attendance_rule/update",
      delete: "api/employee_attendance_rule/delete",
      checkExistCode: "api/employee_attendance_rule/checked_exit_code"
    },
    attRuleDetail: {
      list: "api/employee_attendance_rule_detail/list",
      create: "api/employee_attendance_rule_detail/create",
      update: "api/employee_attendance_rule_detail/update",
      delete: "api/employee_attendance_rule_detail/delete",
      find: "api/employee_attendance_rule_detail/find",
    },
    employeeScanLog: {
      list: "api/employee_scan_log/list",
      report: "api/employee_scan_log/report",
    },
    entitlement: {
      clearingOn: "api/al_entitlement/clearing_on",
      clearingMethod: "api/al_entitlement/clearing_method",
      list: "api/al_entitlement/list",
      create: "api/al_entitlement/create",
      update: "api/al_entitlement/update",
      delete: "api/al_entitlement/delete",
      checkExistCode: "api/al_entitlement/check_exist_code",
    },
    leaveType: {
      list: "api/leavetype/list",
      create: "api/leavetype/create",
      update: "api/leavetype/update",
      delete: "api/leavetype/delete",
      checkCodeExist: "api/leavetype/existcode",
      checkSymbolExist: "api/leavetype/existsymbol",
      rowOrder: "api/leavetype/row_order",

    },
    ALBalance: {
      list: "api/albalance/list",
      get: "api/albalance/get",
    },
    leaveRequest: {
      list: "api/employee_request_leave/list",
      create: "api/employee_request_leave/create",
      update: "api/employee_request_leave/update",
      detail: "api/employee_request_leave/detail",
      request: "api/employee_request_leave/request",
      approve: "api/employee_request_leave/approve",
      reject: "api/employee_request_leave/reject",
      review: "api/employee_request_leave/review",
      delete: "api/employee_request_leave/delete",
      requestShift: "api/employee_request_leave/request_shift",
      historyRequestApprover:
        "api/employee_request_leave/history_request_approver",
      requestApprover: "api/employee_request_leave/request_approver",
      reportListing: "api/employee_request_leave/report_listing",
      reportSummary: "api/employee_request_leave/report_summary",
    },
    schedule: {
      list: "api/workingschedule/list",
      create: "api/workingschedule/create",
      update: "api/workingschedule/update",
      delete: "api/workingschedule/delete",
      detail: "api/workingschedule/detail",
      setDayOff: "api/workingschedule/setdayoff",
      calendar: "api/workingschedule/calendar",
      employeeList: "api/workingschedule/employeelist",
    },
  },

  // period: {
  //   list: "api/accounting/period/list",
  //   create: "api/accounting/period/create",
  //   next: "api/accounting/period/next",
  //   block: "api/accounting/period/block",
  // },

  humanResource: {
    employee: {
      listBasic: "api/employee/list_basic",
      list: "api/employee/list",
      detail: "api/employee/detail",
      create: "api/employee/create",
      update: "api/employee/update",
      updateWorkStatus: "api/employee/update_work_status",
      delete: "api/employee/delete",
      updateImage: "api/employee/update_image",
      removeImage: "api/employee/remove_image",
      printCard: "api/employee/printcard",
      employeeListingReport: "api/employee/listing_report",
      checkEmployeeCode: "api/employee/checkexistedcode",
      checkEmployeeIdentity: "api/employee/check_exist_identity",
      getEmployeeProperty: "api/employee/get_employee_property",
      workInformation: "api/employee/work_information",
      addFileSignature: "api/employee/add_file_signature",
      getSignature: "api/employee/get_signature",
      deleteSignature: "api/employee/delete_signature",
      generalInfo: "api/employee/general_info",
      updateGeneralInfo: "api/employee/update_general_info",
      workingInfo: "api/employee/working_info",
      updateWorkingInfo: "api/employee/update_working_info",
      governmentAndContact: "api/employee/government_and_contact",
      updateGovernAndContact: "api/employee/update_government_and_contact",
      employeeAddress: "api/employee/address",
      updateAddress: "api/employee/update_address",
      isInputEmployeeCode: "api/employee/is_input_employee_code",
      education: {
        list: "api/education/list",
        create: "api/education/create",
        update: "api/education/update",
        delete: "api/education/delete",
      },
      training: {
        list: "api/training/list",
        create: "api/training/create",
        update: "api/training/update",
        delete: "api/training/delete",
      },
      experience: {
        list: "api/experience/list",
        create: "api/experience/create",
        update: "api/experience/update",
        delete: "api/experience/delete",
      },
      family: {
        list: "api/employee_family/list",
        create: "api/employee_family/create",
        update: "api/employee_family/update",
        delete: "api/employee_family/delete",
      },
      contact: {
        list: "api/emergency_contact/list",
        create: "api/emergency_contact/create",
        update: "api/emergency_contact/update",
        delete: "api/emergency_contact/delete",
      },
      reward: {
        list: "api/award_reward/list",
        create: "api/award_reward/create",
        update: "api/award_reward/update",
        delete: "api/award_reward/delete",
        uploadImage: "api/award_reward/upload_image",
      },
      document: {
        list: "api/employee_document/list",
        create: "api/employee_document/create",
        update: "api/employee_document/update",
        delete: "api/employee_document/delete",
        uploadImage: "api/employee_document/upload_image",
        deleteImage: "api/employee_document/delete_image",
      },
      language: {
        list: "api/language/list",
        create: "api/language/create",
        update: "api/language/update",
        delete: "api/language/delete",
      },
      hobby: {
        list: "api/hobby/list",
        create: "api/hobby/create",
        update: "api/hobby/update",
        delete: "api/hobby/delete",
      },
      bank: {
        list: 'api/employeebank/list',
        create: 'api/employeebank/create',
        update: 'api/employeebank/update',
        delete: 'api/employeebank/delete',
      },
      empTypeAddress: {
        birth: "BIRTH",
        current: "CURRENT",
        permanence: "PERMANENCE",
      },
    },
    publicHoliday: {
      year: "api/publicholiday/listyear",
      list: "api/publicholiday/list",
      create: "api/publicholiday/create",
      update: "api/publicholiday/update",
      delete: "api/publicholiday/delete",
      import: "api/publicholiday/import",
      checkExistDate: "api/publicholiday/existdate",
    },
    transferRequest: {
      list: "api/transfer_request/list",
      listEmp: "api/transfer_request/list_employee",
      detail: "api/transfer_request/detail",
      request: "api/transfer_request/request",
      delete: "api/transfer_request/delete",
    },
    transferApproval: {
      list: "api/transfer_request/list",
      detail: "api/transfer_request/detail",
      approve: "api/transfer_request/approve",
      reject: "api/transfer_request/reject",
      review: "api/transfer_request/review",
      helper: "api/transfer_request/helper",
      delete: "api/transfer_request/delete",
      transferRequestFilter: "api/transfer_request/transfer_request_filter",
    },
    employeeBranch: {
      list: "api/employee/branch/list",
      create: "api/employee/branch/create",
      update: "api/employee/branch/update",
      delete: "api/employee/branch/delete",
      transfer: "api/employee/branch/transfer",
      updateStatus: "api/employee/branch/update_status",
      getEmployeeDatabaseRule: "api/employee/branch/get_employee_database_rule",
      setEmployeeBrand: "api/employee/branch/set_employee_brand",
    },

    division: {
      list: "api/division/list",
      create: "api/division/create",
      update: "api/division/update",
      delete: "api/division/delete",
      publicList: "api/division/list/public",
      checkExistedCode: "api/division/checkexistedcode",
      read: "api/division/read",
    },
    department: {
      list: "api/department/list",
      create: "api/department/create",
      update: "api/department/update",
      delete: "api/department/delete",
      read: "api/department/read",
      publicList: "api/department/list/public",
      checkExistedCode: "api/department/checkexistedcode",
    },
    section: {
      list: "api/section/list",
      publicList: "api/section/list/public",
      create: "api/section/create",
      update: "api/section/update",
      read: "api/section/read",
      delete: "api/section/delete",
      checkExistedCode: "api/section/checkexistedcode",
    },
    position: {
      list: "api/position/list",
      publicList: "api/position/list/public",
      create: "api/position/create",
      update: "api/position/update",
      read: "api/position/read",
      delete: "api/position/delete",
      checkExistedCode: "api/position/checkexistedcode",
    },
    bank: {
      list: 'api/banklist/list',
      create: 'api/banklist/create',
      update: 'api/banklist/update',
      delete: 'api/banklist/delete',
      checkExistedCode: 'api/banklist/checkexistedcode',
    },
    nationality: {
      list: "api/nationality/list",
      create: "api/nationality/create",
      update: "api/nationality/update",
      delete: "api/nationality/delete",
      validateCode: "api/nationality/validatecode",
    },
    // address: {
    //   list: "api/address/get",
    //   count: "api/address/count",
    //   create: "api/address/create",
    //   update: "api/address/update",
    //   delete: "api/address/delete",
    //   validateCode: "api/address/validatecode",
    //   countryKey: "COUNTRYS",
    //   provinceKey: "PROVINCES",
    //   districtKey: "DISTRICTS",
    //   communeKey: "COMMUNES",
    //   villageKey: "VILLAGES",
    //   addressType: "CURRENT",
    // },
    monthlyAttendance: {
      List: "api/monthlyattendance/list",
    },
  },
  studentAttendance: {
    attendanceRule: {
      delete: "/api/attendance_rule/delete",
    },
  },
  moduleTeacher: {
    examScore: {
      listExamStudent: "/api/examscore/findbyexam",
      grade: "/api/gradingdetail/list",
      requestApproved: "/api/examrequest/request",
      setScore: "/api/examscore/setscore",
      setComment: "/api/exam_comment/save_exam_comment",
      listDetailBySubject: "/api/exam_score/list_detail",
      getComment: "/api/exam_comment/find",
      addException: "/api/exam_except/create",
      removeException: "/api/exam_except/delete",
    },
    examResult: {
      listExam: "/api/exam_result/class_result_by_subject",
      listResult: "/api/exam_result/class_result_by_exam",
    },
  },

  studentExam: {
    examSetupLearning: {
      learningSubjectList:
        "/api/exam_setup_learning_subject/learning_subject_list",
    },
    academicYearExam: {
      // list setup
      listSetup: "api/academic_year_exam/list_setup",
      addSetup: "api/academic_year_exam/add_setup",
      changeGradingSystem: "api/academic_year_exam/change_grading_system",
      deleteSetup: "api/academic_year_exam/delete_setup",

      // list detail
      list: "api/academic_year_exam/list",
      add: "api/academic_year_exam/add",
      update: "api/academic_year_exam/update",
      delete: "api/academic_year_exam/delete",
      checkExistExamCode: "api/academic_year_exam/check_exist_exam_code",
      recalcScorePercent: "api/academic_year_exam/recalc_score_percent",

      // exam setup
      examSetupList: "api/academic_year_exam/exam_setup_add_list",
      examList: "api/academic_year_exam/exam_add_list",
    },
    examSetup: {
      list: "api/exam_subject_setup/list",
      create: "api/exam_subject_setup/create",
      update: "api/exam_subject_setup/update",
      delete: "api/exam_subject_setup/delete",
      checkCode: "api/exam_subject_setup/checkcode",
      clone: "api/exam_subject_setup/clone",
    },
    gradingSystem: {
      list: "api/gradingsystem/list",
      create: "api/gradingsystem/create",
      update: "api/gradingsystem/update",
      delete: "api/gradingsystem/delete",
      checkCode: "api/gradingsystem/checkcode",
      checkName: "api/gradingsystem/checkname",
    },
  },
  student: {
    scheduleChangeClass: {
      List: "api/schedule_change_class/list",
      Create: "api/schedule_change_class/create",
      Update: "api/schedule_change_class/update",
      Delete: "api/schedule_change_class/delete",
      Run: "api/schedule_change_class/run",
    },
  },
  payroll: {
    salaryLabel: {
      list: "api/salary_label/list",
      update: "api/salary_label/update",
      clear: "api/salary_label/clear",
      listMigrateBranch: "api/salary_label/list_migrate_branch",
      migrate: "api/salary_label/migrate",
    },
    salaryGrading: {
      list: "api/salary_grade/list",
      checkExistCode: "api/salary_grade/check_exist_code",
      create: "api/salary_grade/create",
      update: "api/salary_grade/update",
      delete: "api/salary_grade/delete",
    },
  },
  academicSetting: {
    academicYear: {
      list: "/api/academy/list",
    },
    class: {
      list: "api/classinfo/list",
      create: "api/classinfo/create",
      update: "api/classinfo/update",
      delete: "api/classinfo/delete",
      checkedCode: "api/classinfo/checkedcode",
    },
    courseStudy: {
      program: {
        list: "/api/program/listfilter",
      },
      course: {
        list: "/api/course/filter",
      },
      batch: "/api/coursestudy/listbatchfilter",
      list: "/api/coursestudy/listfilter",
    },
    department: {
      list: "/api/coursedepartment/listfilter",
    },
    subject: {
      learningSubject: {
        list: "api/learningsubject/list",
      },
      subjectType: {
        list: "/api/subjectType/list",
      },
    },
  },

  evaluation: {
    evaluation: {
      listClass: "api/evaluation/list_class",
      listStudent: "api/evaluation/list_student",
      create: "api/evaluation/create",
      update: "api/evaluation/list_student",
      delete: "api/evaluation/delete",
      report: "api/evaluation/report",
    },
  },
  canteen:{
    cash:{
      listCashier:'api/cashreceipt/listcashier',
    },
    cashCollection:{
      list:'api/canteen_cash_collection/list',
      listDetail:"api/cash_collection/list",
      detailList:'api/canteen_cash_collection/detail',
      receiptSummary:"api/cash_collection/receipt_summary",
      create:"api/cash_collection/create",
      receiptFormReport:"api/cash_collection/receipt_form_report",
      annaulList:'api/canteen_cash_collection/actual_detail'
    }
  },
   payroll: {
      salaryLabel: {
        list: 'api/salary_label/list',
        update: 'api/salary_label/update',
        clear: 'api/salary_label/clear',
        listMigrateBranch: 'api/salary_label/list_migrate_branch',
        migrate: 'api/salary_label/migrate',
      },
      salaryGrading: {
        list: 'api/salary_grade/list',
        checkExistCode: 'api/salary_grade/check_exist_code',
        create: 'api/salary_grade/create',
        update: 'api/salary_grade/update',
        delete: 'api/salary_grade/delete',
      },
      currency: {
        list: 'api/payroll/currency/list',
        create: 'api/payroll/currency/create',
        update: 'api/payroll/currency/update',
        delete: 'api/payroll/currency/delete',
        checkCodeExist: 'api/payroll/currency/check_code_exist',
        getBaseCurrency: 'api/payroll/currency/get_base',
      },
      currencyNote: {
        list: 'api/payroll/currency/note/list',
        create: 'api/payroll/currency/note/create',
        update: 'api/payroll/currency/note/update',
        delete: 'api/payroll/currency/note/delete',
      },
      exchangeRate: {
        list: 'api/payroll/exchange_rate/list',
        get: 'api/payroll/exchange_rate/get',
        create: 'api/payroll/exchange_rate/create',
        update: 'api/payroll/exchange_rate/update',
        delete: 'api/payroll/exchange_rate/delete',
      },
      salaryManagement: {
        list: 'api/payroll/salary_management/list',
        create: 'api/payroll/salary_management/create',
        update: 'api/payroll/salary_management/update',
        delete: 'api/payroll/salary_management/delete',
        employeeList: 'api/payroll/salary_management/employeelist',
        basicSalary: 'api/payroll/salary_management/basicsalary',
      },
      seniorityBonusRange:{
        list: "api/senioritybonusrange/list",
        create: "api/senioritybonusrange/create",
        update: "api/senioritybonusrange/update",
        delete: "api/senioritybonusrange/delete",
        migrate: "api/senioritybonusrange/migrate",
        clear: "api/senioritybonusrange/clear",
        listMigrateBranch: "api/senioritybonusrange/list_migrate_branch",
        checkCodeExist: "api/senioritybonusrange/existcode",
      },
      taxCalculationRange:{
        list: "api/taxcalculationrange/list",
        create: "api/taxcalculationrange/create",
        update: "api/taxcalculationrange/update",
        delete: "api/taxcalculationrange/delete",
        migrate: "api/taxcalculationrange/migrate",
        clear: "api/taxcalculationrange/clear",
        listMigrateBranch: "api/taxcalculationrange/list_migrate_branch",
        checkCodeExist: "api/taxcalculationrange/existcode",
      },
    },
};

export default apis;
